//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloommeApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SocialNetworkEntities2 : DbContext
    {
        public SocialNetworkEntities2()
            : base("name=SocialNetworkEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SN_Areas> SN_Areas { get; set; }
        public virtual DbSet<SN_Category> SN_Category { get; set; }
        public virtual DbSet<SN_ChartMessages> SN_ChartMessages { get; set; }
        public virtual DbSet<SN_Commision> SN_Commision { get; set; }
        public virtual DbSet<SN_CustomerJobs> SN_CustomerJobs { get; set; }
        public virtual DbSet<SN_Customers> SN_Customers { get; set; }
        public virtual DbSet<SN_CustomerWallet> SN_CustomerWallet { get; set; }
        public virtual DbSet<SN_Dispute> SN_Dispute { get; set; }
        public virtual DbSet<SN_Invitation> SN_Invitation { get; set; }
        public virtual DbSet<SN_Invoices> SN_Invoices { get; set; }
        public virtual DbSet<SN_Jobs> SN_Jobs { get; set; }
        public virtual DbSet<SN_Messages> SN_Messages { get; set; }
        public virtual DbSet<SN_Payments> SN_Payments { get; set; }
        public virtual DbSet<SN_PostComments> SN_PostComments { get; set; }
        public virtual DbSet<SN_Proposals> SN_Proposals { get; set; }
        public virtual DbSet<SN_ProviderAreas> SN_ProviderAreas { get; set; }
        public virtual DbSet<SN_ProviderBanks> SN_ProviderBanks { get; set; }
        public virtual DbSet<SN_ProviderCategory> SN_ProviderCategory { get; set; }
        public virtual DbSet<SN_ProviderCertification> SN_ProviderCertification { get; set; }
        public virtual DbSet<SN_ProviderDocuments> SN_ProviderDocuments { get; set; }
        public virtual DbSet<SN_ProviderEducation> SN_ProviderEducation { get; set; }
        public virtual DbSet<SN_ProviderJobs> SN_ProviderJobs { get; set; }
        public virtual DbSet<SN_ProviderKeyWords> SN_ProviderKeyWords { get; set; }
        public virtual DbSet<SN_ProviderPackages> SN_ProviderPackages { get; set; }
        public virtual DbSet<SN_ProviderPictures> SN_ProviderPictures { get; set; }
        public virtual DbSet<SN_ProviderRating> SN_ProviderRating { get; set; }
        public virtual DbSet<SN_ProviderReceipt> SN_ProviderReceipt { get; set; }
        public virtual DbSet<SN_Providers> SN_Providers { get; set; }
        public virtual DbSet<SN_ProviderTypes> SN_ProviderTypes { get; set; }
        public virtual DbSet<SN_ProviderVideo> SN_ProviderVideo { get; set; }
        public virtual DbSet<SN_Settlement> SN_Settlement { get; set; }
        public virtual DbSet<SN_Skills> SN_Skills { get; set; }
        public virtual DbSet<SN_Social> SN_Social { get; set; }
        public virtual DbSet<SN_SocialEducation> SN_SocialEducation { get; set; }
        public virtual DbSet<SN_SocialEmployements> SN_SocialEmployements { get; set; }
        public virtual DbSet<SN_SocialFriends> SN_SocialFriends { get; set; }
        public virtual DbSet<SN_SocialPosts> SN_SocialPosts { get; set; }
        public virtual DbSet<SN_Subscription> SN_Subscription { get; set; }
        public virtual DbSet<SN_SubscriptionInvoice> SN_SubscriptionInvoice { get; set; }
        public virtual DbSet<SN_SubscriptionPayment> SN_SubscriptionPayment { get; set; }
        public virtual DbSet<SYS_Banks> SYS_Banks { get; set; }
        public virtual DbSet<SYS_Company> SYS_Company { get; set; }
        public virtual DbSet<SYS_Country> SYS_Country { get; set; }
        public virtual DbSet<SYS_Degrees> SYS_Degrees { get; set; }
        public virtual DbSet<SYS_Roles> SYS_Roles { get; set; }
        public virtual DbSet<SYS_Users> SYS_Users { get; set; }
        public virtual DbSet<SN_SocialLogs> SN_SocialLogs { get; set; }
        public virtual DbSet<SYS_AccountType> SYS_AccountType { get; set; }
        public virtual DbSet<SN_ProviderProfile> SN_ProviderProfile { get; set; }
        public virtual DbSet<SN_VW_Areas> SN_VW_Areas { get; set; }
        public virtual DbSet<SN_vw_Category> SN_vw_Category { get; set; }
        public virtual DbSet<SN_vw_ChartMessages> SN_vw_ChartMessages { get; set; }
        public virtual DbSet<SN_vw_CustomerJobs> SN_vw_CustomerJobs { get; set; }
        public virtual DbSet<SN_vw_Customers> SN_vw_Customers { get; set; }
        public virtual DbSet<SN_vw_Dispute> SN_vw_Dispute { get; set; }
        public virtual DbSet<SN_vw_Invoices> SN_vw_Invoices { get; set; }
        public virtual DbSet<SN_vw_Jobs> SN_vw_Jobs { get; set; }
        public virtual DbSet<SN_vw_Messages> SN_vw_Messages { get; set; }
        public virtual DbSet<SN_VW_Payments> SN_VW_Payments { get; set; }
        public virtual DbSet<SN_vw_PostComments> SN_vw_PostComments { get; set; }
        public virtual DbSet<SN_vw_Proposals> SN_vw_Proposals { get; set; }
        public virtual DbSet<SN_vw_ProviderAreas> SN_vw_ProviderAreas { get; set; }
        public virtual DbSet<SN_vw_ProviderBanks> SN_vw_ProviderBanks { get; set; }
        public virtual DbSet<SN_vw_ProviderCategory> SN_vw_ProviderCategory { get; set; }
        public virtual DbSet<SN_vw_ProviderCertification> SN_vw_ProviderCertification { get; set; }
        public virtual DbSet<SN_VW_ProviderDocuments> SN_VW_ProviderDocuments { get; set; }
        public virtual DbSet<SN_vw_ProviderEducation> SN_vw_ProviderEducation { get; set; }
        public virtual DbSet<SN_VW_ProviderJobs> SN_VW_ProviderJobs { get; set; }
        public virtual DbSet<SN_vw_ProviderKeyWords> SN_vw_ProviderKeyWords { get; set; }
        public virtual DbSet<SN_vw_ProviderPackages> SN_vw_ProviderPackages { get; set; }
        public virtual DbSet<SN_VW_ProviderPictures> SN_VW_ProviderPictures { get; set; }
        public virtual DbSet<SN_VW_ProviderRating> SN_VW_ProviderRating { get; set; }
        public virtual DbSet<SN_vw_ProviderReceipt> SN_vw_ProviderReceipt { get; set; }
        public virtual DbSet<SN_vw_Providers> SN_vw_Providers { get; set; }
        public virtual DbSet<SN_VW_ProviderTypes> SN_VW_ProviderTypes { get; set; }
        public virtual DbSet<SN_VW_ProviderVideo> SN_VW_ProviderVideo { get; set; }
        public virtual DbSet<SN_VW_ProviderVideos> SN_VW_ProviderVideos { get; set; }
        public virtual DbSet<SN_vw_Skills> SN_vw_Skills { get; set; }
        public virtual DbSet<SN_vw_SocialEducation> SN_vw_SocialEducation { get; set; }
        public virtual DbSet<SN_vw_SocialEmployements> SN_vw_SocialEmployements { get; set; }
        public virtual DbSet<SN_VW_SocialFriends> SN_VW_SocialFriends { get; set; }
        public virtual DbSet<SN_vw_SocialProfile> SN_vw_SocialProfile { get; set; }
        public virtual DbSet<SN_vw_Subscription> SN_vw_Subscription { get; set; }
        public virtual DbSet<SN_vw_SubscriptionInvoice> SN_vw_SubscriptionInvoice { get; set; }
        public virtual DbSet<SN_vw_SubscriptionPayment> SN_vw_SubscriptionPayment { get; set; }
        public virtual DbSet<SYS_VW_AccountType> SYS_VW_AccountType { get; set; }
        public virtual DbSet<SYS_VW_Banks> SYS_VW_Banks { get; set; }
        public virtual DbSet<SYS_VW_Country> SYS_VW_Country { get; set; }
        public virtual DbSet<SYS_VW_Degrees> SYS_VW_Degrees { get; set; }
        public virtual DbSet<SYS_vw_Roles> SYS_vw_Roles { get; set; }
        public virtual DbSet<SYS_VW_Users> SYS_VW_Users { get; set; }
        public virtual DbSet<SN_CommissionRate> SN_CommissionRate { get; set; }
        public virtual DbSet<SN_ProviderWallet> SN_ProviderWallet { get; set; }
        public virtual DbSet<SN_vw_Commission> SN_vw_Commission { get; set; }
    
        public virtual ObjectResult<ProviderPictures_Fetch_Result> ProviderPictures_Fetch(Nullable<int> providerPictureID)
        {
            var providerPictureIDParameter = providerPictureID.HasValue ?
                new ObjectParameter("ProviderPictureID", providerPictureID) :
                new ObjectParameter("ProviderPictureID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProviderPictures_Fetch_Result>("ProviderPictures_Fetch", providerPictureIDParameter);
        }
    
        public virtual ObjectResult<SN_VW_Areas> SN_Areas_Fetch(Nullable<int> areaID)
        {
            var areaIDParameter = areaID.HasValue ?
                new ObjectParameter("AreaID", areaID) :
                new ObjectParameter("AreaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_VW_Areas>("SN_Areas_Fetch", areaIDParameter);
        }
    
        public virtual ObjectResult<SN_VW_Areas> SN_Areas_Fetch(Nullable<int> areaID, MergeOption mergeOption)
        {
            var areaIDParameter = areaID.HasValue ?
                new ObjectParameter("AreaID", areaID) :
                new ObjectParameter("AreaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_VW_Areas>("SN_Areas_Fetch", mergeOption, areaIDParameter);
        }
    
        public virtual ObjectResult<SN_Areas_FetchByCategoryID_Result> SN_Areas_FetchByCategoryID(Nullable<int> categoryID, Nullable<int> areaID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            var areaIDParameter = areaID.HasValue ?
                new ObjectParameter("AreaID", areaID) :
                new ObjectParameter("AreaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Areas_FetchByCategoryID_Result>("SN_Areas_FetchByCategoryID", categoryIDParameter, areaIDParameter);
        }
    
        public virtual ObjectResult<SN_Areas_FetchByName_Result> SN_Areas_FetchByName(string areaName)
        {
            var areaNameParameter = areaName != null ?
                new ObjectParameter("AreaName", areaName) :
                new ObjectParameter("AreaName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Areas_FetchByName_Result>("SN_Areas_FetchByName", areaNameParameter);
        }
    
        public virtual ObjectResult<SN_Areas_FetchName_Result> SN_Areas_FetchName(string areaName)
        {
            var areaNameParameter = areaName != null ?
                new ObjectParameter("AreaName", areaName) :
                new ObjectParameter("AreaName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Areas_FetchName_Result>("SN_Areas_FetchName", areaNameParameter);
        }
    
        public virtual ObjectResult<SN_Category_Fetch_Result> SN_Category_Fetch(Nullable<int> categoryID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Category_Fetch_Result>("SN_Category_Fetch", categoryIDParameter);
        }
    
        public virtual ObjectResult<SN_ChartMessages_Fetch_Result> SN_ChartMessages_Fetch(Nullable<int> chartMessageID)
        {
            var chartMessageIDParameter = chartMessageID.HasValue ?
                new ObjectParameter("ChartMessageID", chartMessageID) :
                new ObjectParameter("ChartMessageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ChartMessages_Fetch_Result>("SN_ChartMessages_Fetch", chartMessageIDParameter);
        }
    
        public virtual ObjectResult<SN_ChartMessages_FetchByInterval_Result> SN_ChartMessages_FetchByInterval(Nullable<int> socialID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ChartMessages_FetchByInterval_Result>("SN_ChartMessages_FetchByInterval", socialIDParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<SN_CustomerJobs_Fetch_Result> SN_CustomerJobs_Fetch(Nullable<int> customerPostID)
        {
            var customerPostIDParameter = customerPostID.HasValue ?
                new ObjectParameter("CustomerPostID", customerPostID) :
                new ObjectParameter("CustomerPostID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_CustomerJobs_Fetch_Result>("SN_CustomerJobs_Fetch", customerPostIDParameter);
        }
    
        public virtual ObjectResult<SN_CustomerJobs_FetchActive_Result> SN_CustomerJobs_FetchActive(Nullable<int> customerPostID)
        {
            var customerPostIDParameter = customerPostID.HasValue ?
                new ObjectParameter("CustomerPostID", customerPostID) :
                new ObjectParameter("CustomerPostID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_CustomerJobs_FetchActive_Result>("SN_CustomerJobs_FetchActive", customerPostIDParameter);
        }
    
        public virtual ObjectResult<SN_CustomerJobs_FetchByCustomerID_Result> SN_CustomerJobs_FetchByCustomerID(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_CustomerJobs_FetchByCustomerID_Result>("SN_CustomerJobs_FetchByCustomerID", customerIDParameter);
        }
    
        public virtual ObjectResult<SN_Customers_Fetch_Result> SN_Customers_Fetch(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Customers_Fetch_Result>("SN_Customers_Fetch", customerIDParameter);
        }
    
        public virtual ObjectResult<SN_Customers_FetchCustomerByEmail_Result> SN_Customers_FetchCustomerByEmail(string emailAddress)
        {
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Customers_FetchCustomerByEmail_Result>("SN_Customers_FetchCustomerByEmail", emailAddressParameter);
        }
    
        public virtual ObjectResult<SN_Customers_FetchCustomerByPassword_Result> SN_Customers_FetchCustomerByPassword(string customerPassword)
        {
            var customerPasswordParameter = customerPassword != null ?
                new ObjectParameter("CustomerPassword", customerPassword) :
                new ObjectParameter("CustomerPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Customers_FetchCustomerByPassword_Result>("SN_Customers_FetchCustomerByPassword", customerPasswordParameter);
        }
    
        public virtual ObjectResult<SN_CustomerWallet_FetchByCustomerID_Result> SN_CustomerWallet_FetchByCustomerID(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_CustomerWallet_FetchByCustomerID_Result>("SN_CustomerWallet_FetchByCustomerID", customerIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SN_CustomerWallet_FetchSummary(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SN_CustomerWallet_FetchSummary", customerIDParameter);
        }
    
        public virtual ObjectResult<SN_Dispute_Fetch_Result> SN_Dispute_Fetch(Nullable<int> disputeID)
        {
            var disputeIDParameter = disputeID.HasValue ?
                new ObjectParameter("DisputeID", disputeID) :
                new ObjectParameter("DisputeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Dispute_Fetch_Result>("SN_Dispute_Fetch", disputeIDParameter);
        }
    
        public virtual ObjectResult<SN_Dispute_FetchByCustomerID_Result> SN_Dispute_FetchByCustomerID(Nullable<int> jobID, Nullable<int> customerID)
        {
            var jobIDParameter = jobID.HasValue ?
                new ObjectParameter("JobID", jobID) :
                new ObjectParameter("JobID", typeof(int));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Dispute_FetchByCustomerID_Result>("SN_Dispute_FetchByCustomerID", jobIDParameter, customerIDParameter);
        }
    
        public virtual ObjectResult<SN_Dispute_FetchByProviderID_Result> SN_Dispute_FetchByProviderID(Nullable<int> jobID, Nullable<int> providerID)
        {
            var jobIDParameter = jobID.HasValue ?
                new ObjectParameter("JobID", jobID) :
                new ObjectParameter("JobID", typeof(int));
    
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Dispute_FetchByProviderID_Result>("SN_Dispute_FetchByProviderID", jobIDParameter, providerIDParameter);
        }
    
        public virtual ObjectResult<SN_Friends_FetchPendingReqeust_Result> SN_Friends_FetchPendingReqeust(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Friends_FetchPendingReqeust_Result>("SN_Friends_FetchPendingReqeust", socialIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SN_GetSocialID(Nullable<int> iD, string type)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SN_GetSocialID", iDParameter, typeParameter);
        }
    
        public virtual int SN_Invitation_Fetch(Nullable<int> invitationID)
        {
            var invitationIDParameter = invitationID.HasValue ?
                new ObjectParameter("InvitationID", invitationID) :
                new ObjectParameter("InvitationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SN_Invitation_Fetch", invitationIDParameter);
        }
    
        public virtual ObjectResult<SN_Invoices_Fetch_Result> SN_Invoices_Fetch(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Invoices_Fetch_Result>("SN_Invoices_Fetch", invoiceIDParameter);
        }
    
        public virtual ObjectResult<SN_Invoices_FetchByCustomerID_Result> SN_Invoices_FetchByCustomerID(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Invoices_FetchByCustomerID_Result>("SN_Invoices_FetchByCustomerID", customerIDParameter);
        }
    
        public virtual ObjectResult<SN_Jobs_Fetch_Result> SN_Jobs_Fetch(Nullable<int> jobID)
        {
            var jobIDParameter = jobID.HasValue ?
                new ObjectParameter("JobID", jobID) :
                new ObjectParameter("JobID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Jobs_Fetch_Result>("SN_Jobs_Fetch", jobIDParameter);
        }
    
        public virtual ObjectResult<SN_Jobs_FetchByCustomerID_Result> SN_Jobs_FetchByCustomerID(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Jobs_FetchByCustomerID_Result>("SN_Jobs_FetchByCustomerID", customerIDParameter);
        }
    
        public virtual ObjectResult<SN_Jobs_FetchByProviderID_Result> SN_Jobs_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Jobs_FetchByProviderID_Result>("SN_Jobs_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_Messages_Fetch_Result> SN_Messages_Fetch(Nullable<int> messageID)
        {
            var messageIDParameter = messageID.HasValue ?
                new ObjectParameter("MessageID", messageID) :
                new ObjectParameter("MessageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Messages_Fetch_Result>("SN_Messages_Fetch", messageIDParameter);
        }
    
        public virtual ObjectResult<SN_Messages_FetchByCustomerID_Result> SN_Messages_FetchByCustomerID(Nullable<int> customerID, Nullable<int> jobID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var jobIDParameter = jobID.HasValue ?
                new ObjectParameter("JobID", jobID) :
                new ObjectParameter("JobID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Messages_FetchByCustomerID_Result>("SN_Messages_FetchByCustomerID", customerIDParameter, jobIDParameter);
        }
    
        public virtual ObjectResult<SN_Messages_FetchByProviderID_Result> SN_Messages_FetchByProviderID(Nullable<int> providerID, Nullable<int> jobID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            var jobIDParameter = jobID.HasValue ?
                new ObjectParameter("JobID", jobID) :
                new ObjectParameter("JobID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Messages_FetchByProviderID_Result>("SN_Messages_FetchByProviderID", providerIDParameter, jobIDParameter);
        }
    
        public virtual ObjectResult<SN_Payments_Fetch_Result> SN_Payments_Fetch(Nullable<int> paymentID)
        {
            var paymentIDParameter = paymentID.HasValue ?
                new ObjectParameter("PaymentID", paymentID) :
                new ObjectParameter("PaymentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Payments_Fetch_Result>("SN_Payments_Fetch", paymentIDParameter);
        }
    
        public virtual ObjectResult<SN_Payments_FetchByCustomerID_Result> SN_Payments_FetchByCustomerID(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Payments_FetchByCustomerID_Result>("SN_Payments_FetchByCustomerID", customerIDParameter);
        }
    
        public virtual ObjectResult<SN_PostComments_Fetch_Result> SN_PostComments_Fetch(Nullable<int> postCommentID)
        {
            var postCommentIDParameter = postCommentID.HasValue ?
                new ObjectParameter("PostCommentID", postCommentID) :
                new ObjectParameter("PostCommentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_PostComments_Fetch_Result>("SN_PostComments_Fetch", postCommentIDParameter);
        }
    
        public virtual ObjectResult<SN_PostComments_FetchByPostID_Result> SN_PostComments_FetchByPostID(Nullable<int> postID)
        {
            var postIDParameter = postID.HasValue ?
                new ObjectParameter("PostID", postID) :
                new ObjectParameter("PostID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_PostComments_FetchByPostID_Result>("SN_PostComments_FetchByPostID", postIDParameter);
        }
    
        public virtual ObjectResult<SN_Proposals_Fetch_Result> SN_Proposals_Fetch(Nullable<int> proposalID)
        {
            var proposalIDParameter = proposalID.HasValue ?
                new ObjectParameter("ProposalID", proposalID) :
                new ObjectParameter("ProposalID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Proposals_Fetch_Result>("SN_Proposals_Fetch", proposalIDParameter);
        }
    
        public virtual ObjectResult<SN_Proposals_FetchByCustomerID_Result> SN_Proposals_FetchByCustomerID(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Proposals_FetchByCustomerID_Result>("SN_Proposals_FetchByCustomerID", customerIDParameter);
        }
    
        public virtual ObjectResult<SN_Proposals_FetchByProviderID_Result> SN_Proposals_FetchByProviderID(Nullable<int> providerId)
        {
            var providerIdParameter = providerId.HasValue ?
                new ObjectParameter("ProviderId", providerId) :
                new ObjectParameter("ProviderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Proposals_FetchByProviderID_Result>("SN_Proposals_FetchByProviderID", providerIdParameter);
        }
    
        public virtual ObjectResult<SN_ProviderAreas_Fetch_Result> SN_ProviderAreas_Fetch(Nullable<int> providerAreaID)
        {
            var providerAreaIDParameter = providerAreaID.HasValue ?
                new ObjectParameter("ProviderAreaID", providerAreaID) :
                new ObjectParameter("ProviderAreaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderAreas_Fetch_Result>("SN_ProviderAreas_Fetch", providerAreaIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderAreas_FetchByProviderID_Result> SN_ProviderAreas_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderAreas_FetchByProviderID_Result>("SN_ProviderAreas_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderAreas_FetchByProviderIDAndCategoryID_Result> SN_ProviderAreas_FetchByProviderIDAndCategoryID(Nullable<int> categoryID, Nullable<int> providerID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderAreas_FetchByProviderIDAndCategoryID_Result>("SN_ProviderAreas_FetchByProviderIDAndCategoryID", categoryIDParameter, providerIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderBanks> SN_ProviderBanks_Fetch(Nullable<int> providerBankID)
        {
            var providerBankIDParameter = providerBankID.HasValue ?
                new ObjectParameter("ProviderBankID", providerBankID) :
                new ObjectParameter("ProviderBankID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderBanks>("SN_ProviderBanks_Fetch", providerBankIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderBanks> SN_ProviderBanks_Fetch(Nullable<int> providerBankID, MergeOption mergeOption)
        {
            var providerBankIDParameter = providerBankID.HasValue ?
                new ObjectParameter("ProviderBankID", providerBankID) :
                new ObjectParameter("ProviderBankID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderBanks>("SN_ProviderBanks_Fetch", mergeOption, providerBankIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderBanks> SN_ProviderBanks_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderBanks>("SN_ProviderBanks_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderBanks> SN_ProviderBanks_FetchByProviderID(Nullable<int> providerID, MergeOption mergeOption)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderBanks>("SN_ProviderBanks_FetchByProviderID", mergeOption, providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderCategory_Fetch_Result> SN_ProviderCategory_Fetch(Nullable<int> providerCategoryID)
        {
            var providerCategoryIDParameter = providerCategoryID.HasValue ?
                new ObjectParameter("ProviderCategoryID", providerCategoryID) :
                new ObjectParameter("ProviderCategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderCategory_Fetch_Result>("SN_ProviderCategory_Fetch", providerCategoryIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderCertification> SN_ProviderCategory_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderCertification>("SN_ProviderCategory_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderCertification> SN_ProviderCategory_FetchByProviderID(Nullable<int> providerID, MergeOption mergeOption)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderCertification>("SN_ProviderCategory_FetchByProviderID", mergeOption, providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderCertification_Fetch_Result> SN_ProviderCertification_Fetch(Nullable<int> providerCertificationID)
        {
            var providerCertificationIDParameter = providerCertificationID.HasValue ?
                new ObjectParameter("ProviderCertificationID", providerCertificationID) :
                new ObjectParameter("ProviderCertificationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderCertification_Fetch_Result>("SN_ProviderCertification_Fetch", providerCertificationIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderCertification> SN_ProviderCertification_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderCertification>("SN_ProviderCertification_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderCertification> SN_ProviderCertification_FetchByProviderID(Nullable<int> providerID, MergeOption mergeOption)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderCertification>("SN_ProviderCertification_FetchByProviderID", mergeOption, providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderDocuments_Fetch_Result> SN_ProviderDocuments_Fetch(Nullable<int> providerDocumentID)
        {
            var providerDocumentIDParameter = providerDocumentID.HasValue ?
                new ObjectParameter("ProviderDocumentID", providerDocumentID) :
                new ObjectParameter("ProviderDocumentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderDocuments_Fetch_Result>("SN_ProviderDocuments_Fetch", providerDocumentIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderDocuments_FetchByProviderID_Result> SN_ProviderDocuments_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderDocuments_FetchByProviderID_Result>("SN_ProviderDocuments_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderEducation_Fetch_Result> SN_ProviderEducation_Fetch(Nullable<int> providerEducationID)
        {
            var providerEducationIDParameter = providerEducationID.HasValue ?
                new ObjectParameter("ProviderEducationID", providerEducationID) :
                new ObjectParameter("ProviderEducationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderEducation_Fetch_Result>("SN_ProviderEducation_Fetch", providerEducationIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderEducation_FetchByProviderID_Result> SN_ProviderEducation_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderEducation_FetchByProviderID_Result>("SN_ProviderEducation_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderJobs_Fetch_Result> SN_ProviderJobs_Fetch(Nullable<int> providerJobID)
        {
            var providerJobIDParameter = providerJobID.HasValue ?
                new ObjectParameter("ProviderJobID", providerJobID) :
                new ObjectParameter("ProviderJobID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderJobs_Fetch_Result>("SN_ProviderJobs_Fetch", providerJobIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderKeyWords_Fetch_Result> SN_ProviderKeyWords_Fetch(Nullable<int> providerKeyWordID)
        {
            var providerKeyWordIDParameter = providerKeyWordID.HasValue ?
                new ObjectParameter("ProviderKeyWordID", providerKeyWordID) :
                new ObjectParameter("ProviderKeyWordID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderKeyWords_Fetch_Result>("SN_ProviderKeyWords_Fetch", providerKeyWordIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderKeyWords> SN_ProviderKeyWords_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderKeyWords>("SN_ProviderKeyWords_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderKeyWords> SN_ProviderKeyWords_FetchByProviderID(Nullable<int> providerID, MergeOption mergeOption)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderKeyWords>("SN_ProviderKeyWords_FetchByProviderID", mergeOption, providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderPackages_Fetch_Result> SN_ProviderPackages_Fetch(Nullable<int> providerPackageID)
        {
            var providerPackageIDParameter = providerPackageID.HasValue ?
                new ObjectParameter("ProviderPackageID", providerPackageID) :
                new ObjectParameter("ProviderPackageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderPackages_Fetch_Result>("SN_ProviderPackages_Fetch", providerPackageIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderPackages> SN_ProviderPackages_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderPackages>("SN_ProviderPackages_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_ProviderPackages> SN_ProviderPackages_FetchByProviderID(Nullable<int> providerID, MergeOption mergeOption)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_ProviderPackages>("SN_ProviderPackages_FetchByProviderID", mergeOption, providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderPictures_Fetch_Result> SN_ProviderPictures_Fetch(Nullable<int> providerPictureID)
        {
            var providerPictureIDParameter = providerPictureID.HasValue ?
                new ObjectParameter("ProviderPictureID", providerPictureID) :
                new ObjectParameter("ProviderPictureID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderPictures_Fetch_Result>("SN_ProviderPictures_Fetch", providerPictureIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderPictures_FetchByProviderID_Result> SN_ProviderPictures_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderPictures_FetchByProviderID_Result>("SN_ProviderPictures_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderRating_Fetch_Result> SN_ProviderRating_Fetch(Nullable<int> providerRating)
        {
            var providerRatingParameter = providerRating.HasValue ?
                new ObjectParameter("ProviderRating", providerRating) :
                new ObjectParameter("ProviderRating", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderRating_Fetch_Result>("SN_ProviderRating_Fetch", providerRatingParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sn_providerRating_Summary(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sn_providerRating_Summary", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderReceipt_FetchByProviderID_Result> SN_ProviderReceipt_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderReceipt_FetchByProviderID_Result>("SN_ProviderReceipt_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SN_ProviderReceipt_FetchSummary(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SN_ProviderReceipt_FetchSummary", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_Providers_Fetch_Result> SN_Providers_Fetch(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Providers_Fetch_Result>("SN_Providers_Fetch", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_Providers_FetchByArea_Result> SN_Providers_FetchByArea(Nullable<int> areaID)
        {
            var areaIDParameter = areaID.HasValue ?
                new ObjectParameter("AreaID", areaID) :
                new ObjectParameter("AreaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Providers_FetchByArea_Result>("SN_Providers_FetchByArea", areaIDParameter);
        }
    
        public virtual int SN_Providers_FetchByCategory(Nullable<int> categoryID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SN_Providers_FetchByCategory", categoryIDParameter);
        }
    
        public virtual ObjectResult<SN_Providers_FetchProfile_Result> SN_Providers_FetchProfile(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Providers_FetchProfile_Result>("SN_Providers_FetchProfile", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_Providers_FetchProviderByEmail_Result> SN_Providers_FetchProviderByEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Providers_FetchProviderByEmail_Result>("SN_Providers_FetchProviderByEmail", emailParameter);
        }
    
        public virtual ObjectResult<SN_Providers_FetchProviderByPassword_Result> SN_Providers_FetchProviderByPassword(string providerPassword)
        {
            var providerPasswordParameter = providerPassword != null ?
                new ObjectParameter("ProviderPassword", providerPassword) :
                new ObjectParameter("ProviderPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Providers_FetchProviderByPassword_Result>("SN_Providers_FetchProviderByPassword", providerPasswordParameter);
        }
    
        public virtual ObjectResult<SN_Providers_Search_Result> SN_Providers_Search(string searchWord)
        {
            var searchWordParameter = searchWord != null ?
                new ObjectParameter("SearchWord", searchWord) :
                new ObjectParameter("SearchWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Providers_Search_Result>("SN_Providers_Search", searchWordParameter);
        }
    
        public virtual ObjectResult<SN_ProviderTypes_Fetch_Result> SN_ProviderTypes_Fetch(Nullable<int> providerTypeID)
        {
            var providerTypeIDParameter = providerTypeID.HasValue ?
                new ObjectParameter("ProviderTypeID", providerTypeID) :
                new ObjectParameter("ProviderTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderTypes_Fetch_Result>("SN_ProviderTypes_Fetch", providerTypeIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderVideo_Fetch_Result> SN_ProviderVideo_Fetch(Nullable<int> providerVideoID)
        {
            var providerVideoIDParameter = providerVideoID.HasValue ?
                new ObjectParameter("ProviderVideoID", providerVideoID) :
                new ObjectParameter("ProviderVideoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderVideo_Fetch_Result>("SN_ProviderVideo_Fetch", providerVideoIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderVideo_FetchByProviderID_Result> SN_ProviderVideo_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderVideo_FetchByProviderID_Result>("SN_ProviderVideo_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_Skills_Fetch_Result> SN_Skills_Fetch(Nullable<int> skillID)
        {
            var skillIDParameter = skillID.HasValue ?
                new ObjectParameter("SkillID", skillID) :
                new ObjectParameter("SkillID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Skills_Fetch_Result>("SN_Skills_Fetch", skillIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_Skills> SN_Skills_FetchByProvider(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_Skills>("SN_Skills_FetchByProvider", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_vw_Skills> SN_Skills_FetchByProvider(Nullable<int> providerID, MergeOption mergeOption)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_vw_Skills>("SN_Skills_FetchByProvider", mergeOption, providerIDParameter);
        }
    
        public virtual int SN_Social_Fetch(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SN_Social_Fetch", socialIDParameter);
        }
    
        public virtual ObjectResult<SN_Social_FetchProfilePicture_Result> SN_Social_FetchProfilePicture(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Social_FetchProfilePicture_Result>("SN_Social_FetchProfilePicture", socialIDParameter);
        }
    
        public virtual ObjectResult<SN_Social_FetchSearch_Result> SN_Social_FetchSearch(string searchString)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Social_FetchSearch_Result>("SN_Social_FetchSearch", searchStringParameter);
        }
    
        public virtual ObjectResult<SN_Social_FetchSuggestedFriend_Result> SN_Social_FetchSuggestedFriend(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Social_FetchSuggestedFriend_Result>("SN_Social_FetchSuggestedFriend", socialIDParameter);
        }
    
        public virtual ObjectResult<SN_SocialEducation_Fetch_Result> SN_SocialEducation_Fetch(Nullable<int> socialEducationID)
        {
            var socialEducationIDParameter = socialEducationID.HasValue ?
                new ObjectParameter("SocialEducationID", socialEducationID) :
                new ObjectParameter("SocialEducationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SocialEducation_Fetch_Result>("SN_SocialEducation_Fetch", socialEducationIDParameter);
        }
    
        public virtual ObjectResult<SN_SocialEducation_FetchBySocialID_Result> SN_SocialEducation_FetchBySocialID(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SocialEducation_FetchBySocialID_Result>("SN_SocialEducation_FetchBySocialID", socialIDParameter);
        }
    
        public virtual ObjectResult<SN_SocialEmployements_Fetch_Result> SN_SocialEmployements_Fetch(Nullable<int> socialJobID)
        {
            var socialJobIDParameter = socialJobID.HasValue ?
                new ObjectParameter("SocialJobID", socialJobID) :
                new ObjectParameter("SocialJobID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SocialEmployements_Fetch_Result>("SN_SocialEmployements_Fetch", socialJobIDParameter);
        }
    
        public virtual ObjectResult<SN_SocialEmployements_FetchBySocialID_Result> SN_SocialEmployements_FetchBySocialID(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SocialEmployements_FetchBySocialID_Result>("SN_SocialEmployements_FetchBySocialID", socialIDParameter);
        }
    
        public virtual ObjectResult<SN_SocialFriend_FetchOnlineList_Result> SN_SocialFriend_FetchOnlineList(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SocialFriend_FetchOnlineList_Result>("SN_SocialFriend_FetchOnlineList", socialIDParameter);
        }
    
        public virtual ObjectResult<SN_SocialFriends_Fetch_Result> SN_SocialFriends_Fetch(Nullable<int> socialFriendID)
        {
            var socialFriendIDParameter = socialFriendID.HasValue ?
                new ObjectParameter("SocialFriendID", socialFriendID) :
                new ObjectParameter("SocialFriendID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SocialFriends_Fetch_Result>("SN_SocialFriends_Fetch", socialFriendIDParameter);
        }
    
        public virtual ObjectResult<SN_SocialFriends_FetchBySocialID_Result> SN_SocialFriends_FetchBySocialID(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SocialFriends_FetchBySocialID_Result>("SN_SocialFriends_FetchBySocialID", socialIDParameter);
        }
    
        public virtual ObjectResult<SN_SocialLogs_FetchMostRecent_Result> SN_SocialLogs_FetchMostRecent(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SocialLogs_FetchMostRecent_Result>("SN_SocialLogs_FetchMostRecent", socialIDParameter);
        }
    
        public virtual int SN_SocialPosts_Fetch(Nullable<int> socialPostID)
        {
            var socialPostIDParameter = socialPostID.HasValue ?
                new ObjectParameter("SocialPostID", socialPostID) :
                new ObjectParameter("SocialPostID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SN_SocialPosts_Fetch", socialPostIDParameter);
        }
    
        public virtual ObjectResult<SN_SocialPosts_FetchByFriend_Result> SN_SocialPosts_FetchByFriend(Nullable<int> socialID)
        {
            var socialIDParameter = socialID.HasValue ?
                new ObjectParameter("SocialID", socialID) :
                new ObjectParameter("SocialID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SocialPosts_FetchByFriend_Result>("SN_SocialPosts_FetchByFriend", socialIDParameter);
        }
    
        public virtual ObjectResult<SN_Subscription_Fetch_Result> SN_Subscription_Fetch(Nullable<int> subscriptionID)
        {
            var subscriptionIDParameter = subscriptionID.HasValue ?
                new ObjectParameter("SubscriptionID", subscriptionID) :
                new ObjectParameter("SubscriptionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Subscription_Fetch_Result>("SN_Subscription_Fetch", subscriptionIDParameter);
        }
    
        public virtual ObjectResult<SN_Subscription_FetchActive_Result> SN_Subscription_FetchActive(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Subscription_FetchActive_Result>("SN_Subscription_FetchActive", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_SubscriptionInvoice_Fetch_Result> SN_SubscriptionInvoice_Fetch(Nullable<int> subscriptionInvoiceID)
        {
            var subscriptionInvoiceIDParameter = subscriptionInvoiceID.HasValue ?
                new ObjectParameter("SubscriptionInvoiceID", subscriptionInvoiceID) :
                new ObjectParameter("SubscriptionInvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SubscriptionInvoice_Fetch_Result>("SN_SubscriptionInvoice_Fetch", subscriptionInvoiceIDParameter);
        }
    
        public virtual ObjectResult<SN_SubscriptionPayment_Fetch_Result> SN_SubscriptionPayment_Fetch(Nullable<int> paymentID)
        {
            var paymentIDParameter = paymentID.HasValue ?
                new ObjectParameter("PaymentID", paymentID) :
                new ObjectParameter("PaymentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_SubscriptionPayment_Fetch_Result>("SN_SubscriptionPayment_Fetch", paymentIDParameter);
        }
    
        public virtual ObjectResult<SYS_AccountType_Fetch_Result> SYS_AccountType_Fetch(Nullable<int> accountTypeID)
        {
            var accountTypeIDParameter = accountTypeID.HasValue ?
                new ObjectParameter("AccountTypeID", accountTypeID) :
                new ObjectParameter("AccountTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYS_AccountType_Fetch_Result>("SYS_AccountType_Fetch", accountTypeIDParameter);
        }
    
        public virtual ObjectResult<SYS_VW_Banks> SYS_Banks_Fetch(Nullable<int> bankID)
        {
            var bankIDParameter = bankID.HasValue ?
                new ObjectParameter("BankID", bankID) :
                new ObjectParameter("BankID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYS_VW_Banks>("SYS_Banks_Fetch", bankIDParameter);
        }
    
        public virtual ObjectResult<SYS_VW_Banks> SYS_Banks_Fetch(Nullable<int> bankID, MergeOption mergeOption)
        {
            var bankIDParameter = bankID.HasValue ?
                new ObjectParameter("BankID", bankID) :
                new ObjectParameter("BankID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYS_VW_Banks>("SYS_Banks_Fetch", mergeOption, bankIDParameter);
        }
    
        public virtual int SYS_Company_Fetch(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SYS_Company_Fetch", companyIDParameter);
        }
    
        public virtual ObjectResult<SYS_Country_Fetch_Result> SYS_Country_Fetch(Nullable<int> countryID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYS_Country_Fetch_Result>("SYS_Country_Fetch", countryIDParameter);
        }
    
        public virtual ObjectResult<SYS_Degrees_Fetch_Result> SYS_Degrees_Fetch(Nullable<int> degreeID)
        {
            var degreeIDParameter = degreeID.HasValue ?
                new ObjectParameter("DegreeID", degreeID) :
                new ObjectParameter("DegreeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYS_Degrees_Fetch_Result>("SYS_Degrees_Fetch", degreeIDParameter);
        }
    
        public virtual ObjectResult<SYS_Roles_Fetch_Result> SYS_Roles_Fetch(Nullable<int> roleID)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYS_Roles_Fetch_Result>("SYS_Roles_Fetch", roleIDParameter);
        }
    
        public virtual ObjectResult<SYS_Users_Fetch_Result> SYS_Users_Fetch(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SYS_Users_Fetch_Result>("SYS_Users_Fetch", userIDParameter);
        }
    
        public virtual ObjectResult<SN_Category_FetchFirstX_Result> SN_Category_FetchFirstX(Nullable<int> number)
        {
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Category_FetchFirstX_Result>("SN_Category_FetchFirstX", numberParameter);
        }
    
        public virtual ObjectResult<SN_Jobs_FetchByType_Result> SN_Jobs_FetchByType(Nullable<int> providerID, Nullable<int> typeID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            var typeIDParameter = typeID.HasValue ?
                new ObjectParameter("TypeID", typeID) :
                new ObjectParameter("TypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Jobs_FetchByType_Result>("SN_Jobs_FetchByType", providerIDParameter, typeIDParameter);
        }
    
        public virtual int SN_Messages_FetchByCustomerIDMobile(Nullable<int> customerID)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SN_Messages_FetchByCustomerIDMobile", customerIDParameter);
        }
    
        public virtual ObjectResult<SN_Messages_FetchByProviderIDMobile_Result> SN_Messages_FetchByProviderIDMobile(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Messages_FetchByProviderIDMobile_Result>("SN_Messages_FetchByProviderIDMobile", providerIDParameter);
        }
    
        public virtual ObjectResult<SN_Payments_FetchByJobID_Result> SN_Payments_FetchByJobID(Nullable<int> jobID)
        {
            var jobIDParameter = jobID.HasValue ?
                new ObjectParameter("JobID", jobID) :
                new ObjectParameter("JobID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Payments_FetchByJobID_Result>("SN_Payments_FetchByJobID", jobIDParameter);
        }
    
        public virtual ObjectResult<SN_Proposals_FetchByCustomerPostID_Result> SN_Proposals_FetchByCustomerPostID(Nullable<int> customerPostID)
        {
            var customerPostIDParameter = customerPostID.HasValue ?
                new ObjectParameter("CustomerPostID", customerPostID) :
                new ObjectParameter("CustomerPostID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_Proposals_FetchByCustomerPostID_Result>("SN_Proposals_FetchByCustomerPostID", customerPostIDParameter);
        }
    
        public virtual ObjectResult<SN_ProviderWallet_FetchByProviderID_Result> SN_ProviderWallet_FetchByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SN_ProviderWallet_FetchByProviderID_Result>("SN_ProviderWallet_FetchByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SN_ProviderWallet_FetchSummary(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("ProviderID", providerID) :
                new ObjectParameter("ProviderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SN_ProviderWallet_FetchSummary", providerIDParameter);
        }
    }
}
