//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloommeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_CommissionRate
    {
        public int CommissionRateID { get; set; }
        public decimal ProviderRate { get; set; }
        public decimal CustomerRate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
