//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloommeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_Dispute
    {
        public int DisputeID { get; set; }
        public int JobID { get; set; }
        public string DisputeMessage { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public string ProviderResponse { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateResponded { get; set; }
        public Nullable<bool> IsAdminApproved { get; set; }
        public Nullable<bool> IsTime { get; set; }
        public Nullable<bool> IsJobSatisfaction { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<decimal> JobCompletionRating { get; set; }
        public Nullable<decimal> ApprovedRating { get; set; }
    }
}
