//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloommeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_Messages
    {
        public int MessageID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Message { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsReade { get; set; }
    }
}
