//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloommeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_ProviderCertification
    {
        public int ProviderCertificationID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public string CertificationName { get; set; }
        public string YearAchived { get; set; }
        public string CertificationProvider { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
