//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloommeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_ProviderProfile
    {
        public int ProviderID { get; set; }
        public Nullable<int> ProviderTypeID { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string MiddleName { get; set; }
        public string CompanyName { get; set; }
        public string ProviderAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string EmailAddress { get; set; }
        public string ProviderPassword { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string JobDescription { get; set; }
        public string KeyWord { get; set; }
        public string SkillName { get; set; }
        public string CertificationName { get; set; }
        public string CategoryName { get; set; }
        public string AreaName { get; set; }
    }
}
