//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloommeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_SocialFriends
    {
        public int SocialFriendID { get; set; }
        public Nullable<int> SocialID { get; set; }
        public Nullable<int> FriendID { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> InvitationID { get; set; }
    }
}
