//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloommeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_SocialEducation
    {
        public int SocialEducationID { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<int> YearFrom { get; set; }
        public Nullable<int> YearTo { get; set; }
        public string DegreeObtained { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Course { get; set; }
    }
}
