//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloommeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_vw_Providers
    {
        public int ProviderID { get; set; }
        public Nullable<int> ProviderTypeID { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string Firstname { get; set; }
        public string AccountTypeName { get; set; }
        public string Lastname { get; set; }
        public string MiddleName { get; set; }
        public string CompanyName { get; set; }
        public string Fullname { get; set; }
        public string ProviderAddress { get; set; }
        public string City { get; set; }
        public string EmailAddress { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string IPAddress { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string ProviderPassword { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public string ProviderTypeName { get; set; }
        public string ProfilePictureURL { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
        public Nullable<bool> IsLogin { get; set; }
    }
}
